let it download linux version instead of non-existent freebsd one
To deal with the following Zed build error on FreeBSD:

error: failed to run custom build command for `webrtc-sys v0.3.5 (https://github.com/zed-industries/rust-sdks?rev=799f10133d93ba2a88642cd480d01ec4da53408c#799f1013)`
Caused by:
  process didn't exit successfully: `/usr/home/jaco/t/software/zed/target/release/build/webrtc-sys-b629d9fe205c2f51/build-script-build` (exit status: 101)
  thread 'main' panicked at /home/jaco/.cargo/git/checkouts/rust-sdks-e9c3cb1fc511908e/799f101/webrtc-sys/build.rs:85:45:
  called `Result::unwrap()` on an `Err` value: "failed to download webrtc from https://github.com/livekit/client-sdk-rust/releases/download/webrtc-dac8015-6/webrtc-freebsd-x64-release.zip: 404 Not Found"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace